# Generated by Django 5.2.6 on 2025-12-14 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(max_length=80)),
                ('cantidad_disponible', models.PositiveIntegerField(default=0)),
                ('unidad', models.CharField(blank=True, max_length=30, null=True)),
                ('marca', models.CharField(max_length=80)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('usuario_red_social', models.CharField(blank=True, max_length=80, null=True)),
                ('descripcion', models.TextField()),
                ('plataforma', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('WHATSAPP', 'WhatsApp'), ('PRESENCIAL', 'Presencial'), ('SITIO_WEB', 'Sitio Web'), ('OTRA', 'Otra')], default='SITIO_WEB', max_length=20)),
                ('fecha_solicitada', models.DateField(blank=True, null=True)),
                ('estado_pedido', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('APROBADO', 'Aprobado'), ('EN_PROCESO', 'En proceso'), ('REALIZADA', 'Realizada'), ('ENTREGADA', 'Entregada'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='SOLICITADO', max_length=20)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=20)),
                ('token_seguimiento', models.CharField(editable=False, max_length=32, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='pedidos/')),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='appTienda.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen_1', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen_2', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen_3', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('destacado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='appTienda.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appTienda.producto'),
        ),
    ]
