# Generated by Django 5.2.6 on 2025-12-15 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTienda', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Insumo',
        ),
        migrations.RemoveField(
            model_name='pedidoimagen',
            name='pedido',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='imagen_1',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio_base',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='destacado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen_2',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen_3',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appTienda.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=125),
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='PedidoImagen',
        ),
    ]
