# Generated by Django 5.2.6 on 2025-12-15 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTienda', '0002_delete_insumo_remove_pedidoimagen_pedido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=125)),
                ('tipo', models.CharField(max_length=100)),
                ('cantidad_disponible', models.IntegerField()),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('marca', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_1',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_2',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_3',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=125)),
                ('cliente_direccion', models.TextField(blank=True, null=True)),
                ('cliente_telefono', models.CharField(max_length=20)),
                ('cliente_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('usuario_red_social', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField()),
                ('fecha_solicitada', models.DateField(blank=True, null=True)),
                ('plataforma_origen', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('WHATSAPP', 'WhatsApp'), ('PRESENCIAL', 'Presencial'), ('SITIO_WEB', 'Sitio Web')], default='SITIO_WEB', max_length=20)),
                ('estado_pedido', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('APROBADO', 'Aprobado'), ('EN_PROCESO', 'En Proceso'), ('REALIZADO', 'Realizado'), ('ENTREGADO', 'Entregado'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=20)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('RECHAZADO', 'Rechazado'), ('PARCIAL', 'Parcial')], default='PENDIENTE', max_length=20)),
                ('imagen_referencia', models.ImageField(blank=True, null=True, upload_to='pedidos/')),
                ('token_seguimiento', models.CharField(editable=False, max_length=32, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appTienda.producto')),
            ],
        ),
    ]
