# Generated by Django 5.2.6 on 2025-12-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTienda', '0003_insumo_remove_producto_imagen_producto_imagen_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='unidad',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('PARCIAL', 'Parcial')], default='PENDIENTE', max_length=20),
        ),
    ]
