# Generated by Django 5.2.6 on 2025-12-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTienda', '0004_remove_insumo_unidad_alter_pedido_estado_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente_direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
